### ISSUE TITLE
News for Puga

### ISSUE THREAD

**Issue by commercialsuicide** [krabradosty/pashkaBlg#24]
в админке есть 2 категории новостей: "zapolnit" и "gotovayaSsylka". рандомным образом с серва должно приходить 2 новости из категории "zapolnit" и 1 из "gotovayaSsylka"
@krabradosty

**Comment by krabradosty** [comment]
зачем ты так по ебаному нызываешь свои новости?

**Comment by krabradosty** [comment]
Уже было все сделано
